version: '3.8'
services:

  nextjs-app:
    image: nextjs-app
    container_name: nextjs-app
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - BACKEND_URL=http://host.docker.internal:8000
    volumes:
      - ./my-app:/my-app
      - node_modules:/node_modules
      - build:.next 
    env_file:
      - .env


volumes:
  node_modules:
  build: