name: ci/cd

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'
      - name: Create .env file
        run: echo "NEXT_PUBLIC_BASE_URL={{secrets.NEXT_PUBLIC_BASE_URL}}" >> .env && echo "BACKEND_URL={{secrets.BACKEND_URL}}" >> .env
      - name: Install Dependencies
        run: npm install
      - name: Run Docker Image Build
        run: docker build -t my-nextjs-app .  

      - name: Run Lint
        run: npm run lint

      - name: Run Build      
        run: npm run build
      -name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      -name: Push to Docker Hub
        run: docker push my-nextjs-app
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:  
      - name: Pull image from Docker Hub
        run: docker pull my-nextjs-app
      - name: Delete old container if exists
        run: docker rm -f nextjs-container
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nextjs-container my-nextjs-app
